[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium==0.14.0",
    "streamlit-folium==0.11.0",
    "streamlit==1.22.0",
    "twilio>=9.5.0",
    "pandas>=2.2.3",
    "numpy>=2.2.3",
]
